BabyProClinicproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('baby/',include('babyapp.urls')),
    path('doc/',include('doctorapp.urls')),
    path('',include('patientapp.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

babyapp/urls.py
from django.urls import path
from .import views
app_name='babyapp'
urlpatterns=[

    path('c',views.indexhome,name='adminlogin'),
    path('adminportal',views.adminportal,name='portal'),
    path('doctorpanel',views.doctorpanel,name='panel'),
    path('doctoradd',views.adddoc,name='add'),
    path('update',views.updatedoc,name='update'),
    

    path('view',views.viewdoc,name='view'),
    path('master',views.master),
    path('p_contact',views.P_contact,name='contact'),
    path('m_delete/<int:mid>',views.deletecontact,name='m_delete'),

    path('i_delete/<int:iid>',views.deletedoctor,name='i_delete'),
    path('upt/<int:sid>',views.upt,name='s_update')
    



    
    
    

    



]

patientapp/urls.py
from django.urls import path
from .import views
app_name='patientapp'
urlpatterns=[
    path('',views.clinichome,name='home'),
    path('patientbooking',views.booking,name='booking'),
    path('view',views.signup,name='signup'),
    path('login/',views.Login,name='login'),
    path('master',views.master),
    path('about',views.aboutus,name='about'),
    path('contact',views.contact,name='contact'),
    path('contact',views.contact,name='contact'),
    path('bookingstatus',views.bookingstatus,name='bookingstatus'),
    
    
    
]                       

patientapp/models.py
from django.db import models

# Create your models here.
class Patient(models.Model):
    name=models.TextField(db_column='name',null=True)
    email=models.TextField(db_column='email',null=True)
    number=models.PositiveBigIntegerField(db_column='number',null=True)
    password=models.TextField(db_column='password',null=True)
    class Meta:
        db_table='patient_registration'
class Booking(models.Model):
    name=models.TextField(db_column='name',null=True)
    number=models.PositiveBigIntegerField(db_column='mob',null=True)
    time=models.TimeField(db_column='time',null=True)
    address=models.TextField(db_column='address',null=True,max_length=500)
    location=models.TextField(db_column='location',null=True)
    specialist=models.TextField(db_column='speciallist',null=True)
    doctors=models.TextField(db_column='doc',null=True)
    msg=models.TextField(db_column='message',null=True)
    status=models.TextField(db_column='status',null=True)
    class Meta:
        db_table='general_booking'
class Contact(models.Model):
    name=models.TextField(db_column='name',null=True)
    email=models.TextField(db_column='email',null=True)
    msg=models.TextField(db_column='msg',null=True)
    class Meta:
        db_table='patient_contact'
    




    

patientapp/views.py
from django.shortcuts import render,redirect
from . models import *

# Create your views here.
def clinichome(request):
    return render(request,'patientapp/clinichomepage.html')
def booking(request):
    if request.method=='POST':
        name=request.POST['name']
        mobile=request.POST['mob']
        time=request.POST['time']
        address=request.POST['address']
        loc=request.POST.get('loc')
        spl=request.POST.get('spl')
        doc=request.POST.get('doct')
        msg=request.POST['message']
        
        booking=Booking(name=name,number=mobile,time=time,address=address,location=loc,specialist=spl,doctors=doc,msg=msg,status='waiting')
        booking.save()
        return redirect('patientapp:booking')
    return render(request,'patientapp/patientbooking.html')
def signup(request):
    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        mobile=request.POST['mob']
        password=request.POST['password']
        patient=Patient(name=name,email=email,number=mobile,password=password)
        patient.save()
        return redirect('patientapp:login')
    return render(request,'patientapp/patientsignup.html')
def Login(request):
    if request.method=='POST':
        username=request.POST['email']
        password=request.POST['password']  
        try:
            patient=Patient.objects.get(email=username,password=password)
        except Patient.DoesNotExist:
            err='invalid email or password'
            return render(request,'patientapp/patientlogin.html',{'err':err})
        return redirect('patientapp:booking')
    return render(request,'patientapp/patientlogin.html')
def master(request):
    return render(request,'patientapp/masterpatient.html')
def aboutus(request):
    return render(request,'patientapp/aboutus.html')
def contact(request):
    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        msg=request.POST['msg']
        contact=Contact(name=name,email=email,msg=msg)
        contact.save()

    return render(request,'patientapp/contactus.html')
def bookingstatus(request):
        booking=Booking.objects.all()
        return render(request,'patientapp/bookingstatus.html',{'booking':booking})



patientapp/templates/patientapp/aboutus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css2?family=Croissant+One&family=DM+Serif+Display:ital@1&family=Dancing+Script:wght@400;500&family=Playfair+Display&display=swap" rel="stylesheet">
    <style>
        .div{
            position: absolute;
            left: 500px;
            top: 60px;
            width: 1200px;
            height: 600px;
            opacity: 0.7;


        }
            
        h1{
            text-align: center;
            color:rgb(26,26,26);
            font-style: italic;
        }
        .p1{
            
            font-size: 30px;
            text-align: center;
            position: absolute;
            top: 850px;
            left: 630px;
            color: rgb(26, 26, 26);
            font-style: italic;
            

        }
        .p1:hover{
            background-color: rgb(116, 235, 235);
        }
        .p2{
            position: absolute;
            top: 900px;


            font-size: 30px;
            text-align: center;
            color: aliceblue;
        }
        .container-fluid{
            background-color: white;
            
        
            
        }
        h2{
            position: absolute;
            top: 20px;
            left: 500px;
            background: -webkit-linear-gradient(rgb(246, 104, 220),rgb(12, 12, 12));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-size: 30px;
    
        }
        .img1{
            position: absolute;
            top: 600px;
            left: 150px;
            filter: drop-shadow(5px 5px rgb(105, 104, 104));
        }
        .img2{
            position: absolute;
            top: 600px;
            left: 600px;
            filter: drop-shadow(5px 5px rgb(105, 104, 104));
        }
        .img3{
            position: absolute;
            top: 600px;
            left: 1000px;
            filter: drop-shadow(5px 5px rgb(105, 104, 104));
            
        }
        .p3{
            position: absolute;
            left: 300px;
            font-style: italic;
            font-size: 30px;
            color:rgb(15, 14, 14) ;
            
            
        }
        .p2{
            position: absolute;
            top: 770px;
            left: 250px;
            color:rgb(26,26,26) ;
        }
        .p5{
            position: absolute;
            left: 700px;
            top: 770px ;
            font-size: 20px;
            color: rgb(26, 26, 26);
        }
        .p4{
            position: absolute;
            left: 1100px;
            top: 770px ;
            font-size: 30px;
            color: rgb(22, 22, 22);
            
        }
        .icon{
            position: absolute;
            top: 30px;
            left: 1400px;
            
        }


    </style>
</head>
<body style="background-image: url(https://media.istockphoto.com/id/1169662101/photo/adult-and-child-hands-holding-red-heart-on-aqua-background-heart-health-donation-csr-concept.jpg?s=612x612&w=0&k=20&c=NSzjKdMvCt4YrTr2PSrq1tIfDPbljz6t7IJ1GQ7bquU=);background-repeat: no-repeat; background-size: cover; height: 1000px;">
    <body style="background-image: url();background-repeat: no-repeat; background-size: cover; height: 1000px;">
    <div class="container-fluid">
        <img src="{% static 'images\pediatric icon.jpg' %}" alt="">
        <h2>PEDIATRIC HOSPITAL MANAGEMENT</h2>
    </div>

    <h1>About Us</h1>
    <p  class="p3">Our Branchs of medicine dealing with the health and medical care of infants,<br> children and adolescents from birth up to the age of 18  our doctots are <br>responsible for helping patients adapt to a hospital setting and prepare<br> them for medical treatment and procedures<br> their plays an important role in the health and wellbeing of ypur child <br> .they have a wide range of responsibilities from conducting regular well-child<br> checkups to diagonosing and treating illness,injuries and other health conditions</p>
    <div>
<img class="img1" src="{% static 'images/hospital0.jpeg' %}" alt="">
<img class="img2" src="{% static 'images/hospital2.jpg' %}" alt="">
<img class="img3" src="{% static 'images/hospital10.jpg' %}" alt="">
    </div>
    
    
<p class="p1">pediatric Helpline <br> 9+9087545667</p>
<p class="p2" >palakkad</p>
<p class="p5">Thrissur</p>
<p class="p4">kozhikkode</p>
<div class="icon">
  <a href="{% url 'patientapp:home' %}"><img src="{% static 'images/home.png' %}" alt=""></a>
  </div>
</body>
</html> 

patientapp/templates/patientapp/bookingstatus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background-image: radial-gradient(skyblue,white);
            height: 700px;
        }
        h1{
            text-align: center;
            color: brown;
        }
        table{
            border: 1px solid rgb(0, 0, 0);
            border-collapse: collapse;
            
        }
        td{
            border: 1px solid rgb(47, 34, 215);
            border-collapse:collapse ;
            padding: 20px;
            width: 300px;
        }
        .h1{
            color: rgb(2, 42, 29);
        }
        .tr{
            color: blueviolet;
        }
    

    </style>
</head>
<body>
    <a href="{% url 'patientapp:home' %}"><img src="{% static 'images/home.png' %}" alt=""></a>
    <h1 class="h1">BookingStatus</h1>
    <table>
        <tr class="tr">
            <td>Name</td>
            <td>Nime</td>
            <td>Status</td>
        </tr>
        {% for i in booking %}
        <tr>
            <td>{{i.name}}</td>
            <td>{{i.time}}</td>
            <td style="color: red;">{{i.status}}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

patientapp/templates/patientapp/clinichomepage.html
{% extends 'patientapp/masterpatient.html' %}
{% load static %}
{% block content %}


<body style="background-image: url(https://www.shriramsinghhospital.com/images/pediatrics-doctor-noida.jpg);background-repeat: no-repeat;background-size: cover;">
   <div class="container">
    <p class="h1">PEDIATRIC <br> HOSPITAL <br> MANAGEMENT </p>
    </div>
    <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'babyapp:adminlogin' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'doctorapp:log' %}">Doctorlogin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'patientapp:signup' %}">Patient</a>
        </li>
      </ul>

  

    </body>
    
    
    {% endblock %}

  

patientapp/templates/patientapp/contactus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/contact.css' %}">
    
</head>
<body style="background-image: url(https://media.istockphoto.com/id/157334654/photo/abstract-red-stripes.jpg?s=612x612&w=0&k=20&c=Gin0ro2wehIu5oqCHHBY7dzbUI55As8mYaFU9JMSt_w=); background-repeat: no-repeat;background-size: cover;">
    <form action="" method="POST">
    {% csrf_token %}
    <div class="div" >
        <h1>Contact Us</h1>
        <input type="text" name="name" id="" placeholder="NAME"><br><br><br><br>
        <input type="text" name="email" id="" placeholder="EMAIL"><br><br><br><br>
        <textarea class="text"   name="msg" id="" cols="30" rows="10">MESSAGE</textarea>
        <button style="background-image: url(https://media.istockphoto.com/id/157334654/photo/abstract-red-stripes.jpg?s=612x612&w=0&k=20&c=Gin0ro2wehIu5oqCHHBY7dzbUI55As8mYaFU9JMSt_w=);">Send your message</button>

    </div>
    <a href="{% url 'patientapp:home' %}"><img src="{% static 'images/home.png' %}" alt=""></a>

</form>
</body>
</html>

patientapp/templates/patientapp/masterpatient.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/masterpatient.css' %}">
    <link rel="stylesheet" href="{% static 'css/clinichomepage.css' %}">
    <link rel="stylesheet" href="{% static 'css/patientbooking.css' %}">
    <link rel="stylesheet" href="{% static 'css/patientsignup.css' %}">
    
    
    <style>
    


    </style>
</head>
<body>
    <nav class="navbar" style="background-color: #BEC0D2;">
        <div class="container-fluid">
          <a href="{% url 'patientapp:home' %}" class="navbar-brand">HOME</a>
          <a href="{% url 'patientapp:about' %}" class="btn button">About Us</a>
          <a href="{% url 'patientapp:contact' %}" class="btn ">Contact us</a>
          
          <form class="d-flex" role="search">
          
            <a href="{% url 'patientapp:signup' %}" class="btn  button">SIGN UP</a>
            <a href="{% url 'patientapp:login' %}" class="btn" >LOG IN</a>

          </form>
        </div>
      </nav>
      {% block content %}

      {% endblock %}
    




      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
      <script src="{% static 'js/singup.js' %}"></script>
</body>
</html>

patientapp/templates/patientapp/patientbooking.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/patientbooking.css' %}">

    <style>
button{
    background-color: rgb(174, 174, 232);
    color: aliceblue;
    border-radius: 10px 10px;
    border-color: rgb(174,174,232);
    width: 100px;
}

/* .form{
    border: 1px solid black;
    width: 250px;
    text-align: center;
} */
.border{
    text-align: center;
    position: absolute;
    top: 130px;
    left: 600px;
    border: 1px solid black;
    height: 500px;
    width: 300px;
    
}
.border:hover{
    background-color: rgb(182, 195, 228);
}
.patnam{
    position: absolute;
    top: 40px;
    left: 66px;
    
}
.sele{
    position: absolute;
    left: 15px;
}
.loc{
    position: absolute;
    left: 110px;
    width: 175px;
}
.time{
    width: 168px;
}
option{
    background-color: rgb(181, 181, 208);
}
textarea:hover{
    background-color: rgb(209, 203, 215);
    

}
.log{
    position: absolute;
    top: 20px;
    color: azure;
    text-decoration: none;
    font-size: 20px;
    border-radius: 10px;
    border: 1px solid rgb(235, 235, 243);
    

}
body{
    background-color: rgb(224, 123, 123);
}
.h1{
    
    color: antiquewhite;
    margin-left: 670px;
    
}
.img{
    width: 40px;
    position: absolute;
    left: 1400px;
    top: 20px;
    border-radius: 10px;

}


    </style>
</head>
<body>

<h1 class="h1">Booking </h1>
    
<a  class="log"  href="{% url 'patientapp:home' %}">Logout</a>
    <form action="" method="post"  name="adminlogin" id="loginform1" onsubmit="return appointmentform()">
        {% csrf_token %}
        <div class="border">
        <input class="patnam" type="text" name="name" id="" placeholder="patient name"><br><br><br><br>
        <input type="text" name="mob" id="" placeholder="Mobile number"><br><br>
        <input class="time" type="time" name="time" id="" placeholder="Timing"><br><br>
        <input type="text" name="address" id="" placeholder="Address"><br><br>
        <label class="sele" for="">select location</label>
        <select class="loc"  name="loc" id="">
            <option value="nil">Select</option>
            <option value="palakkad">palakkad</option>
            <option value="alathur">alathur</option>
            <option value="pattambi">pattambi</option>
            <option value="mannarkkad">mannarkkad</option>
            <option value="ottappalam">ottappalam</option>
            <option value="chittur">chittur</option>
        </select><br><br>
        <label for="">select specialists</label>
        <select name="spl" id=""> 
        <option value="nil">Select</option>
         <option value="generalpediatrics">General pediatrics</option>
         <option value="cardiology">cardiology</option>
         <option value="Gastroenterology">Gastroenterology</option>
         <option value="pediatrichemotology">pediatric hemotology</option>
         
        </select><br><br>

        <label for="">select doctors</label>
        <select name="doct" id="">
        <option value="">Select</option>           
         <option value="dr.sanjeevkumarTM(pediatrician)">Dr.sanjeev kumar T M (pediatrician)</option>
         <option value="Dr.Rose(Gastroenterology)">Dr.Rose (Gastroenterology) </option>
         <option value="Dr.AparnaNamboodiripad(cardiology)">Dr.Aparna Namboodiripad (cardiology)</option>
         <option value="Dr.VimalVincent(hemotology)">Dr.Vimal Vincent (hemotology)</option>
        
        </select><br><br>

        <textarea name="message" id="Message" cols="30" rows="10">Message</textarea><br><br>
        <button type="submit">BOOking</button>
    </div>
    <a href="{% url 'patientapp:bookingstatus' %}"><img class="img" src="{% static 'images/booking.png' %}" alt=""></a>



    </form>
</body>
</html>



patientapp/templates/patientapp/patientlogin.html

{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/patientlogin.css' %}">
    <style>
       
         
       div{
           
           width: 100%;
           height: 800px;
       
           
          
           
       }
       tr{
           text-align: center;
           position: absolute;
           top: 300px;
       }
       td{
           border-bottom: 1px solid rgb(21, 20, 20);
       
       
           
           text-align: center;
       }
       
       .user{
       
           position: absolute;
           top: 10px;
           left: 650px;
           
       }
       .pass{
       position: absolute;
       top: 50px;
       left: 650px;
       }
       h1{
       text-align: center;
       position: absolute;
       top: 200px;
       left: 670px;
       color: antiquewhite;
       
       
       }
       input[type="text"]{
           border: none;
           background-color: pink;
       }
       input[type="password"]{
           border: none;
           background-color: pink;
       }
       form{
           border: 1px solid rgb(113, 101, 101);
       }
       h4{
           position: absolute;
           top: 370px;
           left: 750px;
       }
       .h4{
           position: absolute;
           top: 370px;
           left: 660px;
       }
       button{
           position: absolute;
           left: 660px;
           top: 430px;
           width: 170px;
           border-radius: 10px;
           color: rgb(222, 225, 231);
           background-color: rgb(154, 154, 217);
           
       }
       
       
    </style>
</head>
<body>
 
    <form action="" method="post">
        {% csrf_token %}
        
        <div style="background-image:url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx9lsY5mSUgIPy6Z55BWagBBBQP_OR1XelKg&usqp=CAU);background-repeat: no-repeat;background-size: cover;"> 
        <h1>LOGIN</h1>
        <a href="{% url 'patientapp:home' %}"><img src="{% static 'images/home.png' %}" alt=""></a>
        <table >

            <tr >
                <td class="user"><input type="text" name="email" id="" placeholder="Enter your email"></th>
                </tr>
                <tr>
                <td class="pass"><input type="password" name="password" id="" placeholder="Enter your password"></th>
            </tr>
            {% if err %}
         <p  style="color:red">{{ err }}</p>
           {% endif %} 

        
        </table>
        <a href=""><h4>Forgetpassword </h4> </a>
        <a href="{% url 'patientapp:signup' %}"><h4 class="h4">sign up</h4></a>
        <button type="submit" >LOG IN</button>

    </div>
        
    <input type="submit" value="login">
    </form>
    
    

    
</body>
</html>

patientapp/templates/patientapp/patientsignup.html
{% extends 'patientapp/masterpatient.html' %}
{% load static %}
{% block content %}
<body style="background-image: url(https://images.unsplash.com/photo-1527049979667-990f1d0d8e7f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjM1fHxsb2dpbiUyMGJhY2tncm91bmR8ZW58MHx8MHx8fDA%3D); background-repeat: no-repeat;background-size: cover;">
    

<div class="div1" style="background-image: url(https://images.unsplash.com/photo-1445112098124-3e76dd67983c?q=80&w=867&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
    <h1>SIGN UP </h1>
    
    <form action="" method="post" onsubmit="signupform()">
        {% csrf_token %}
        <table >
            <tr >
            <td><label class="l1" for="">Username</label></td>
            <td><input class="int1" type="text" name="name" id="" placeholder="Username"><br><br><br></td>
            </tr>
            <tr class="l2"> 
                <td><label for="">Email id</label></td>
                <td></tr><input class="int2" type="text" name="email" id="email" placeholder="Email id"><br><br></td>
            </tr>
            
             <tr>
                <label class="l3" for="">Mobilenumber</label>
                <input class="int4" type="number" name="mob" id="pass" placeholder=" Mobilenumber"><br><br>
             </tr>
             <tr>
                <label class="l4" for="">createpassword</label>
                <input class="int5" type="password" name="pass" id="password" placeholder=" createpassword"><br><br>
             </tr>
             <tr>
                <label class="l5" for="">confirmpassword</label>
                <input class="int6" type="password" name="password" id="pass" placeholder=" createpassword"><br><br>
             </tr>
             
             <button  type="submit" class="btn btn-outline-success">SIGNUP</button>
            <p id="error" style="color: red;"></p>
            </table>
    </form>
</div>
</body>
{% endblock %}





