BabyProClinicproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('baby/',include('babyapp.urls')),
    path('doc/',include('doctorapp.urls')),
    path('',include('patientapp.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

babyapp/urls.py
from django.urls import path
from .import views
app_name='babyapp'
urlpatterns=[

    path('c',views.indexhome,name='adminlogin'),
    path('adminportal',views.adminportal,name='portal'),
    path('doctorpanel',views.doctorpanel,name='panel'),
    path('doctoradd',views.adddoc,name='add'),
    path('update',views.updatedoc,name='update'),
    

    path('view',views.viewdoc,name='view'),
    path('master',views.master),
    path('p_contact',views.P_contact,name='contact'),
    path('m_delete/<int:mid>',views.deletecontact,name='m_delete'),

    path('i_delete/<int:iid>',views.deletedoctor,name='i_delete'),
    path('upt/<int:sid>',views.upt,name='s_update')
    



    
    
    

    



]

patientapp/urls.py
from django.urls import path
from .import views
app_name='patientapp'
urlpatterns=[
    path('',views.clinichome,name='home'),
    path('patientbooking',views.booking,name='booking'),
    path('view',views.signup,name='signup'),
    path('login/',views.Login,name='login'),
    path('master',views.master),
    path('about',views.aboutus,name='about'),
    path('contact',views.contact,name='contact'),
    path('contact',views.contact,name='contact'),
    path('bookingstatus',views.bookingstatus,name='bookingstatus'),
    
    
    
]                       

babyapp/models.py
from django.db import models

# Create your models here.
class Adddoctor(models.Model):
    username=models.TextField(db_column='user',null=True)
    password=models.TextField(db_column='pass',null=True)
    doc_id=models.PositiveBigIntegerField(db_column='doc_id',null=True)
    age=models.PositiveIntegerField(db_column='age',null=True)
    image=models.ImageField(upload_to='images', db_column='image',null=True)
    gender=models.TextField(db_column='gen',null=True)
    number=models.PositiveBigIntegerField(db_column='number',null=True)
    class Meta:
        db_table="add_doctor"
    
    




babyapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from . models import *
from patientapp.models import Contact
from django.http import JsonResponse

# Create your views here.
def indexhome(request):
    if request.method=='POST':
        adminuser=request.POST['user']
        adminpassword=request.POST['pass1']
        user=authenticate(request,username=adminuser,password=adminpassword)
        if user is not None:
            login(request,user)  
            return redirect('babyapp:portal')          

            
        else :
            return render (request,'babyapp/adminloginpage.html',{'msg':'invalid username or password'})

            

    return render(request,'babyapp/adminloginpage.html')
def adminportal(request):
    return render(request,'babyapp/adminportal.html')
def doctorpanel(request):
    return render(request,'babyapp/bdoctorpanel.html')
def adddoc(request):
    if request.method=='POST':
          username=request.POST['username']
          password=request.POST['password']
          doc_id=request.POST['roll_no']
          age=request.POST['age']
          image=request.FILES['image']
          gender=request.POST.get('gender')
          number=request.POST['no']


          adddoc=Adddoctor(username=username,password=password,doc_id=doc_id,age=age,image=image,gender=gender,number=number)
          adddoc.save()
          return render(request,'babyapp/doctoraddpage.html',{'para':'doctors added successully'})
    else:
          return render (request,'babyapp/doctoraddpage.html')
def updatedoc(request):
    doc1=Adddoctor.objects.all()
    return render(request,'babyapp/doctorupdatepage.html',{'doc2':doc1})

def viewdoc(request):
    srds=Adddoctor.objects.all()
    
    return render(request,'babyapp/doctorviewpage.html',{'doc':srds})
def deletedoctor(request,iid):
    Adddoctor.objects.get(id=iid).delete()
    return redirect('babyapp:view')
def master(request):
    return render(request,'babyapp/master.html')

def P_contact(request):
    contact_msg=Contact.objects.all()

    return render(request,'babyapp/p_contact.html',{'msg':contact_msg})
def deletecontact(request,mid):
    Contact.objects.get(id=mid).delete()
    return redirect('babyapp:contact')
def upt(request,sid):
    doc= Adddoctor.objects.get(id=sid)
    if request.method=='POST':
          username=request.POST['username']
          password=request.POST['password']
          roll=request.POST['roll_no']
          age=request.POST['age']
        #   image=request.FILES['image']
          gender=request.POST['gender']
          number=request.POST['no']
          doc.username=username
          doc.password=password
          doc.doc_id=roll
          doc.age=age
          doc.gender=gender
          doc.number=number
          doc.save()
          return redirect('babyapp:update')
 
    return render(request,'babyapp/update.html',{'s_update':doc})







babyapp/templates/babyapp/P_contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background-color: rgb(61, 248, 148);
        }
        table{
            border: 1px solid rgb(218, 17, 17);
            border-collapse: collapse;
            text-align: center;
            

        }
        table:hover{
            background-color: rgb(222, 228, 243);
        }
        th{
            border: 1px solid black;
            padding: 20px;
            width: 500px;
            color: blue;
            
        }
        td{
            border: 1px solid black;
            padding: 20px;
            color: rgb(18, 17, 17);
            width: 400px;
            
        }
        .msg:hover,td:hover{
            background-color: rgb(234, 150, 150);
            
        }
        h1{
            text-align: center;
            color: brown;
        }
        .nam{
            width: 100px;

        }
        .img{
            position: absolute;
            top: 0px;
        }
        

    </style>
</head>
<body>
    <h1>Contact List</h1>
    <a href="{% url 'babyapp:portal' %}"><img class="img" src="{% static 'images/home.png' %}" alt=""></a>
    <div>
    <table>
        <tr><th class="nam">Name</th>
        <th>Email</th>
        <th>Message</th>
        <th>Delete</th>
        </tr>
        <tr>
            {% for m in msg  %}
            <td class="nam">{{m.name}}</td>
            <td>{{m.email}}</td>
            <td class="msg">{{m.msg}}</td> 
            <td><a href="{% url 'babyapp:m_delete' m.id %}" class="btn btn-danger">delete</a></td>
            


        </tr>
        {% endfor %}
    </table>
    </div>
</body>
</html>

babyapp/templates/babyapp/adminloginpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin page</title>
    <link rel="stylesheet" href="{% static 'css/adminlogin.css' %}">
    <style>
.and{
    text-decoration: none;
    position: absolute;
    bottom: 670px;
    right: 1390px;
    color: rgb(225, 47, 47);
    font-size: 15px;

}
    </style>

</head>
<body>
    
    <form action="" method="post"  name="adminlogin" id=" loginform1" onsumbit="return loginform()">
        {% csrf_token %}
    <h1>LOGIN PORTAL</h1>
    <div class="form">
    <div class="form1">
    <label class="lable" for="">username</label>
    <input type="text" name="user" id="Admin" ><br><br>
    <label class="lable2" for="">password</label>
    <input type="password" name="pass1" id="Pass" palceholder="password"><br><br>
    <p style="color: red;">{{msg}}</p> 
    <a href=""><button class="btn" type="submit">Login</button></a>
    </div>
    
    <a class= "and" href="{% url 'patientapp:home' %}"><img src="{% static 'images\home.png'%}" alt=""></a>
</div>
</form>
    
        
<script src="{% static 'js/adminlogin.js' %}"></script>
    
</body>
</html>

babyapp/templates/babyapp/adminportal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/admportal.css' %}">
    <style>
.cont{
    position: absolute;
    top: 450px;
    left: 750px;
    border-radius:20px ;
    border-color: aquamarine;

}
.conti{
    position: absolute;
    top: 560px;
    left: 760px;

    border-radius: 20px;
    border-color: aquamarine;
}
.doct{
position: absolute;
     margin-top: 250px;
    margin-left: 500px;
    border-radius: 20px;
    border-color: aquamarine;
 }

    </style>
</head>
<body>
    <div>
        <h1>ADMIN PORTAL</h1>
    </div>
    <a href=""><img class="home" src="{% static 'images\home.png' %}" alt=""></a>
    
    <div>
        <a href="{% url 'babyapp:panel' %}"><img class="doc" src="{% static 'images\Doctor-icon.png' %}" alt=""></a>
        <a href="{% url 'babyapp:panel' %}"><button class="doct">Doctor Panal</button></a>
    </div>
    <div>
       <a href="{% url 'doctorapp:list' %}"><img class="pat" src="{% static 'images\pa.png' %}" alt=""></a>
       <a href="{% url 'doctorapp:list' %}"><button class="pati">Patient list</button></a>
       <div>
        <a href="{% url 'babyapp:contact' %}"><img class="cont" src="{% static 'images\contact.png' %}" alt=""></a>
       <a href="{% url 'babyapp:contact' %}"><button class="conti">contact list</button></a>
       </div>
    
    </div>
</div>
<table>
    <tr>
        
    </tr>
</table>

    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>   
</body>
</html>

babyapp/templates/babyapp/bdoctorpanel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/doctorpanal.css' %}">
</head>
<style>
.img{
    margin-left: 700px;
    margin-top: 2px;
    height: 30px;
    width: 30px;

  }
</style>
<body>
  
    <div>
      
  <a class="img" href="{% url 'patientapp:home' %}"><img src="{% static 'images/home.png' %}" alt=""></a>
</div>
     <div class="div">
         <a href="{% url 'patientapp:home' %}"><img src="{% static 'images\grp.jpeg' %}" class="img-fluid" alt="..."></a>
    </div> 
    <h1>Doctor Panel</h1>
    <ol class="list-group ">
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Add Doctors</div>
            
          </div>
          <a href="{% url 'babyapp:add' %}"><button class="badge bg-primary rounded-pill">Add</button></a>
        </li><br>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Update Doctors </div>
            
          </div><br>
          <a href="{% url 'babyapp:update' %}"><button class="badge bg-primary rounded-pill"> Upt</button></a>
        </li><br>
        
          <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
              <div class="fw-bold">View Doctors</div>

            </div>
            <a href="{% url 'babyapp:view' %}"><button class="badge bg-primary rounded-pill">Viw</button></a>
          </li><br>
      </ol>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>  
</body>
</html>

babyapp/templates/babyapp/doctoraddpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/doctoraddpage.css' %}">
    <style>
        .img{
            position: absolute;
            top:-100px;
            left: 1100px;

        }
    </style>
</head>
<body>
    
    <h1>ADD Doctor</h1>
    <p id="error" style="color: red;"></p> 
    <div class="form" action=" " id="add">
        <p class="para" style="color: rgb(7, 92, 32);">{{para}}</p>
    <form action="" method="POST" id ="clr" novalidate enctype="multipart/form-data">
        {% csrf_token %}
    <label for="">Username</label>
    <input type="text" name="username" id="" placeholder=""><br><br>
    <label for="">password</label>
    <input type="password" name="password" id="pass" placeholder=""><br><br>
    <form class="form" action=""name="" id="clear">
    <label for="">roll no</label>
    <input type="text" name="roll_no" id="" placeholder="id"><br><br>
    <label for="">age</label> 
    <input type="number" name="age" id=""><br><br>
    <label for="">images</label>
    <input type="file" name="image" id="">
    <label for="">gender</label>
    <select name="gender" id="gender">
        <option value="male">male</option>
        <option value="female">female</option>
    

    </select><br><br>
    <label for="">phone number</label>
    <input type="number" name="no" id=""><br><br>
    <button id="clr" onclick="clearbox()">clear</button><br><br>
    <form class="form1" action="" id="add"> 
    <button onclick="addDetails()">ADD</button>
    <a href="{% url 'babyapp:view' %}"><img class="img" src="{% static 'images/view.png' %}" alt=""></a>
    
    </form>
    

</div>
<a href="{% url 'babyapp:panel' %}"><img src="{% static 'images/home.png' %}" alt=""></a>

<script src="{% static 'js/doctoraddjava.js' %}"></script>



</body>
</html>

babyapp/templates/babyapp/doctorupdatepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/updatedoctor.css' %}">
    <style>
        .button{
            color: rgb(69, 67, 67);
            font-size: 20px;
        }
        a{
            text-decoration: none;
            color: green;
        }
    </style>
</head>
<body>
    <h1>Update Doctor Details</h1>
    <table class="tab">
        <tr class="the">
            <th>username</th>
            <th>password</th>
            <th>Id</th>
            <th>Age</th>
            <th>image</th>
            <th>Gender</th>
            <th>Phone Number</th>
            <th>update</th>
            
        </tr>
        
        {% for s in doc2 %}
        <tr>
            <td>{{s.username}}</td>
            <td>{{s.password}}</td>
            <td>{{s.doc_id}}</td>
            <td>{{s.age}}</td>
            <td>{{s.image}}</td>
            <td>{{s.gender}}</td>
            <td>{{s.number}}</td>
    
            <td><a href="{% url 'babyapp:s_update' s.id %}" class="btn btn-danger">update</a></td>

        </tr>
        {% endfor %}
    
        
    </table>
    <a href="{% url 'babyapp:add' %}"><img src="{% static 'images\updatepic.png' %}" alt=""></a>
</body>
</html>

babyapp/templates/babyapp/doctorviewpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link rel="stylesheet" href="{% static 'css/doctorview.css' %}"> -->
    <style>
    table,td,th{
    border: 2px solid black;
    border-collapse: collapse;
    border-color: rgb(70, 70, 71);
    text-align: center;

}
td,th{
    padding: 10px;
    padding-left: 70px;
    

}

h1{
    text-align: center;
    background-image:linear-gradient(rgb(144, 133, 135),rgb(111, 111, 158));
    color: rgb(201, 243, 243);
}
button{
    border-radius: 40px;
    background-color: rgb(175, 195, 207);
    font-size: 15px;
    color: rgb(49, 47, 47);
    margin-left: 500px;
    position: absolute;
    left: 680px;
    top: 519px;
    border-color: rgb(175, 195, 207);
    border-right-color: rgb(175, 195, 207);
    border-bottom-color: rgb(175, 195, 207);
}

body{
    background-image:linear-gradient( rgb(181, 225, 226),rgb(179, 179, 216)) ;
    height: 800px;
}
.the{
    color: rgb(16, 75, 238);
    
}
.upt{
    position: absolute;
top: 90px;
left: 820px;
background-color: rgb(127, 178, 255);
color: red;



}
.dele{
position: absolute;
top: 90px;
left: 740px;
background-color: rgb(127, 178, 255);
color: red;

}
a{
    text-decoration: none;
    color: red;
}
.imag{
    position: absolute;
    top: 20px;
    width: 30px;
    height: 40px;
}





    </style>
</head>
<body>
    <a  href="{% url 'babyapp:panel' %}"><img class="imag"  src="{% static 'images/view.png' %}" alt=""></a>

    <h1>View Doctor Details</h1>
    

    
    <table class="tab">
        <tr class="the">
            <th>username</th>
            <th>password</th>
            <th>Id</th>
            <th>Age</th>
            <th>image</th>
            <th>Gender</th>
            <th>Phone Number</th>
            <th>Image</th>
            <th>Delete</th>
        </tr>
        {%for i in doc%}
        <tr>
            <td>{{i.username}}</td>
            <td>{{i.password}}</td>
            <td>{{i.doc_id}}</td>
            <td>{{i.age}}</td>
            <td>{{i.image}}</td>
            <td>{{i.gender}}</td>
            <td>{{i.number}}</td>
           
            <td>
                {% if i.image %}
                <img src="{{ i.image.url }}" alt="{{ i.username }}" style="max-width: 50px;max-height: 50px;">
                {% else %}
                No image
                {% endif %}
            </td>
    
            <td><a href="{% url 'babyapp:i_delete' i.id %}" class="btn btn-danger">Delete</a></td>

        </tr>
        {% endfor %}
    
    </table>
</body>
</html>

babyapp/templates/babyapp/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/adminlogin.css' %}">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
  </head>
<body>
  
  <nav class="navbar ">
    <div class="container">
      <a class="navbar-brand" href="#">
        <a class="nav" href="{% url 'patientapp:home' %}"><img src="{% static 'images/home.png' %}" alt="Bootstrap" width="30" height="30"></a>
        
      </a>
    </div>
  </nav>
{% block content %}

{% endblock %}


   <div class="container-fluid">
    <div class="row">
      <div class="col-12 footer">
          <p class="p3" style="color: rgb(blue);">@PEDIATRIC HOSPITAL</p>
          <P class="p1">contact:9087653423</P>
          <P class="p2">place:palakkad</P>
      </div>
    </div>
   </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> 
</body>
</html>

babyapp/templates/babyapp/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/update.css' %}">
</head>
<body>
    
    <h1>update Doctor</h1>
    <p id="error" style="color: red;"></p> 
    <div class="form" action=" " id="add">
        <p class="para" style="color: rgb(7, 92, 32);">{{para}}</p>
    <form action="" method="POST" id ="clr" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        
    <label for="">Username</label>
    <input type="text" name="username" id="" placeholder="" value="{{s_update.username}}" ><br><br>
    <label for="">password</label>
    <input type="password" name="password" id="pass" placeholder="" value="{{s_update.password}}" ><br><br>
    <label for="">roll no</label>
    <input type="number" name="roll_no" id="" placeholder="id" value="{{s_update.roll_no}}"  ><br><br>
    <label for="">age</label> 
    <input type="number" name="age" id="" value="{{s_update.age}}" ><br><br>
    <label for="">images</label>
    <input type="file" name="image" id="" value="{{s_update.images}}">
    <label for="">gender</label>
    <select name="gender" id="gender" value="{{s_update.gender}}" >
        <option value="male">male</option>
        <option value="female">female</option>
    

    </select><br><br>
    <label for="">phone number</label>
    <input type="number" name="no"  id=""  value="{{s_update.number}}"><br><br>
    <input type="submit" value="updatedoctor" >
    
    
    
    
    </form>
    

</div>




</body>
</html>